### ISSUE TITLE
undefined method `completed_assignments' for #<Turkee....>

### ISSUE THREAD

**Issue by workmaster2n** [aantix/turkee#13]
When I run `rake turkee:get_all_results` I get this output:

```
rake aborted!
undefined method `completed_assignments' for #<Turkee::TurkeeTask:0x007fd0e3ca3f30>
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/activemodel-3.2.1/lib/active_model/attribute_methods.rb:407:in `method_missing'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.1/lib/active_record/attribute_methods.rb:126:in `method_missing'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/turkee.rb:144:in `check_hit_completeness'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/turkee.rb:58:in `block (2 levels) in process_hits'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.1/lib/active_record/relation/delegation.rb:6:in `each'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.1/lib/active_record/relation/delegation.rb:6:in `each'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/turkee.rb:35:in `block in process_hits'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:275:in `block in lock'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `block (2 levels) in attempt'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `catch'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `block in attempt'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `loop'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:517:in `attempt'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:201:in `lock'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/lockfile-2.1.0/lib/lockfile.rb:191:in `initialize'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/turkee.rb:31:in `new'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/turkee.rb:31:in `process_hits'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/bundler/gems/turkee-42f6f30b0fa9/lib/tasks/turkee.rb:14:in `block (2 levels) in <top (required)>'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/Tyler/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Users/Tyler/.rvm/gems/ruby-1.9.2-p290/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
./bundler_stubs/rake:16:in `load'
./bundler_stubs/rake:16:in `<main>'
Tasks: TOP => turkee:get_all_results
```

`completed_assingments` seems to be an `attr_reader` in `RTurk` `HITParser`:

```
module RTurk

  class HITParser < RTurk::Parser

    attr_reader :id, :type_id, :status, :title, :created_at, :expires_at, :assignments_duration,
                :reward_amount, :max_assignments, :pending_assignments, :available_assignments,
                :completed_assignments, :auto_approval_delay, :keywords

    def initialize(hit_xml)
      @xml_obj = hit_xml
      map_content(@xml_obj,
                  :id => 'HITId',
                  :type_id => 'HITTypeId',
                  :status => 'HITStatus',
                  :title => 'Title',
                  :created_at => 'CreationTime',
                  :expires_at => 'Expiration',
                  :assignments_duration => 'AssignmentDurationInSeconds',
                  :reward_amount => 'Reward/Amount',
                  :max_assignments => 'MaxAssignments',
                  :pending_assignments => 'NumberOfAssignmentsPending',
                  :available_assignments => 'NumberOfAssignmentsAvailable',
                  :completed_assignments => 'NumberOfAssignmentsCompleted',
                  :auto_approval_delay => 'AutoApprovalDelayInSeconds')
    end
  end
end
```

The results from the HIT are being added to my model though.

**Comment by aantix** [comment]
There's been some additional fields added to the turkee_tasks table.  Thanks for pointing this out; I need to provide an upgrade path for this.  Nonetheless, ensure your turkee_tasks table matches the following :

```
create_table "turkee_tasks" do |t|
  t.string   "hit_url"
  t.boolean  "sandbox"
  t.string   "task_type"
  t.text     "hit_title"
  t.text     "hit_description"
  t.string   "hit_id"
  t.decimal  "hit_reward", :precision => 10, :scale => 2
  t.integer  "hit_num_assignments"
  t.integer  "hit_lifetime"
  t.string   "form_url"
  t.integer  "completed_assignments", :default => 0
  t.boolean  "complete"
  t.timestamps
end
```

**Comment by workmaster2n** [comment]
Awesome, thanks!
