### ISSUE TITLE
new_test_path

### ISSUE THREAD

**Issue by alexthegoodman** [aantix/turkee#25]
Hey! If you guys could help, it'd be appreciated. I'm getting this error in the terminal when I try to send out an initial test HIT:

$ rake turkee:post_hit["https://www.yourapp.com","Please complete our survey","Tell us your favorite color.","Test",100,0.05,5,1]
rake aborted!
undefined method `new_test_path' for #<ActionDispatch::Integration::Session:0x007fe66453bd88>
/usr/local/rvm/gems/ruby-2.0.0-p247/gems/actionpack-4.0.0/lib/action_dispatch/testing/assertions/routing.rb:171:in`method_missing'
/Users/macuser/.bundler/ruby/2.0.0/turkee-8cfe9bd96f2f/lib/models/turkee_task.rb:248:in `form_url'
/Users/macuser/.bundler/ruby/2.0.0/turkee-8cfe9bd96f2f/lib/models/turkee_task.rb:241:in`build_url'
/Users/macuser/.bundler/ruby/2.0.0/turkee-8cfe9bd96f2f/lib/models/turkee_task.rb:71:in `create_hit'
/Users/macuser/.bundler/ruby/2.0.0/turkee-8cfe9bd96f2f/lib/tasks/turkee.rb:7:in`block (2 levels) in <top (required)>'
Tasks: TOP => turkee:post_hit

I'm having difficulty assessing how to deal with new_test_path. If you need more information, or if this an error that isn't the result of my doing, please let me know! 

Thanks guys, and thanks for your work on this nice library

**Comment by aantix** [comment]
In the above example, it assumes that there's a resource called "Test".  Do you have that setup?
